/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IntroductionMaterialImport } from './routes/introduction/material'
import { Route as IntroductionExerciseImport } from './routes/introduction/exercise'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IntroductionMaterialRoute = IntroductionMaterialImport.update({
  id: '/introduction/material',
  path: '/introduction/material',
  getParentRoute: () => rootRoute,
} as any)

const IntroductionExerciseRoute = IntroductionExerciseImport.update({
  id: '/introduction/exercise',
  path: '/introduction/exercise',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/introduction/exercise': {
      id: '/introduction/exercise'
      path: '/introduction/exercise'
      fullPath: '/introduction/exercise'
      preLoaderRoute: typeof IntroductionExerciseImport
      parentRoute: typeof rootRoute
    }
    '/introduction/material': {
      id: '/introduction/material'
      path: '/introduction/material'
      fullPath: '/introduction/material'
      preLoaderRoute: typeof IntroductionMaterialImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/introduction/exercise': typeof IntroductionExerciseRoute
  '/introduction/material': typeof IntroductionMaterialRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/introduction/exercise': typeof IntroductionExerciseRoute
  '/introduction/material': typeof IntroductionMaterialRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/introduction/exercise': typeof IntroductionExerciseRoute
  '/introduction/material': typeof IntroductionMaterialRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/introduction/exercise' | '/introduction/material'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/introduction/exercise' | '/introduction/material'
  id: '__root__' | '/' | '/introduction/exercise' | '/introduction/material'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntroductionExerciseRoute: typeof IntroductionExerciseRoute
  IntroductionMaterialRoute: typeof IntroductionMaterialRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntroductionExerciseRoute: IntroductionExerciseRoute,
  IntroductionMaterialRoute: IntroductionMaterialRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/introduction/exercise",
        "/introduction/material"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/introduction/exercise": {
      "filePath": "introduction/exercise.tsx"
    },
    "/introduction/material": {
      "filePath": "introduction/material.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
